services:
    postgres:
        build:
            context: ./
            dockerfile: ./Dockerfile.db-service
        env_file: .env
        stop_grace_period: 10s
        volumes:
            - data_postgres:/var/lib/postgresql/data
        ports:
            - "${POSTGRES_EXT_PORT:-5432}:5432"

    fuseki:
        build:
            context: ./
            dockerfile: ./Dockerfile.sparql-service
        command: --tdb2 --update --loc databases/DB2 --set tdb:unionDefaultGraph=true /ds
        ports:
            - ${FUSEKI_EXT_PORT:-3030}:3030

    web:
        build:
            context: ./
            dockerfile: ./Dockerfile.web-service
        #command: flask db upgrade
        #command: flask run --host=0.0.0.0
        command: ./startup.sh
        env_file: .env
        volumes:
            - ./source/web-service/flaskapp:/app/flaskapp
            - ./source/web-service/tests:/app/tests
            - ./source/web-service/migrations:/app/migrations
        ports:
            - "${FLASK_RUN_PORT:-5100}:${FLASK_RUN_PORT:-5100}"  # Flask HTTP port
            - "${VSCODE_DEBUG_PORT:-5001}:5001"  # For VS Code debugger

volumes:
    data_postgres:
