version: "3.7"

services:
    postgres:
        build:
            context: ./
            dockerfile: ./Dockerfile.db-service
        env_file: .env
        stop_grace_period: 10s
        volumes:
            - data_postgres:/var/lib/postgresql/data
        ports:
            - 5432:5432

    web:
        build:
            context: ./
            dockerfile: ./Dockerfile.web-service
        command: flask run --host=0.0.0.0
        env_file: .env
        volumes:
            - ./source/web-service/flaskapp:/app/flaskapp
            - ./source/web-service/tests:/app/tests
            - ./source/web-service/migrations:/app/migrations
        ports:
            - "${FLASK_RUN_PORT}:5100"
            - "5001:5001"  # VS Code debugger

volumes:
    data_postgres:
