version: "3.0"

services:
    postgres:
        build:
            context: ./
            dockerfile: ./services/postgres/Dockerfile
        environment:
            POSTGRES_HOST:     ${POSTGRES_HOST}
            POSTGRES_USER:     ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB:       ${POSTGRES_DB}
            POSTGRES_PORT:     ${POSTGRES_PORT}
            PGDATA:            ${POSTGRES_PGDATA}
            TZ:                ${TIMEZONE}
        ports:
            - "${POSTGRES_PORT}:5432"
        stop_grace_period: 10s
        # stop_signal: SIGTERM
        volumes:
            - data_postgres:/var/lib/postgresql/data

    transformer:
        build:
            context: ./
            dockerfile: ./source/transformer/Dockerfile
        environment:
            LD_LIBRARY_PATH:   /usr/local/lib:/usr/local/lib64
            SHELL:             ${SHELL}
            TZ:                ${TIMEZONE}
            POSTGRES_HOST:     ${POSTGRES_HOST}
            POSTGRES_PORT:     ${POSTGRES_PORT}
            POSTGRES_USER:     ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB:       ${POSTGRES_DB}
            NEPTUNE_HOST:      ${NEPTUNE_HOST}
            NEPTUNE_PORT:      ${NEPTUNE_PORT}
            NEPTUNE_ENDPOINT:  ${NEPTUNE_ENDPOINT}
            DOR_BASE_URL:      ${DOR_BASE_URL}
            DOR_FIND_URL:      ${DOR_FIND_URL}
            DOR_API_USER:      ${DOR_API_USER}
            DOR_API_KEY:       ${DOR_API_KEY}
            DOR_API_VERSION:   ${DOR_API_VERSION}
            DOR_API_CACHING:   ${DOR_API_CACHING}
            LOD_BASE_URL:      ${LOD_BASE_URL}
            LOD_SLASH_URL:     ${LOD_SLASH_URL}
        volumes:
            # use a volume mount to dynamically bind the application's source code
            - ./source/transformer/startup.py:/startup.py
            - ./source/transformer/startup.sh:/startup.sh
            - ./source/transformer/app:/app
            - ./source/transformer/tests:/tests
            # use a volume mount to dynamically bind the shared dependency injector code
            - ./source/app/di:/app/di
            # use a volume mount to dynamically bind the shared database code
            - ./source/app/database:/app/database
            # use a volume mount to dynamically bind the shared graph store code
            - ./source/app/graph:/app/graph
            # use a volume mount to dynamically bind the shared model code
            - ./source/app/model:/app/model
            # use a volume mount to dynamically bind the shared utilities code
            - ./source/app/utilities:/app/utilities
            # use a volume mount to dynamically bind the data path
            - ./data:/usr/local/mart/data
            # use a volume mount to dynamically bind the tests path
            - ./tests:/usr/local/mart/tests
        ports:
            - "${TRANSFORMER_PORT}:5200"
        links:
            - postgres:postgres
        stdin_open: true
        tty: true

    web:
        build:
            context: ./
            dockerfile: ./source/web-service/Dockerfile
        environment:
            LD_LIBRARY_PATH:   /usr/local/lib:/usr/local/lib64
            SHELL:             ${SHELL}
            TZ:                ${TIMEZONE}
            POSTGRES_HOST:     ${POSTGRES_HOST}
            POSTGRES_PORT:     ${POSTGRES_PORT}
            POSTGRES_USER:     ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB:       ${POSTGRES_DB}
            NEPTUNE_HOST:      ${NEPTUNE_HOST}
            NEPTUNE_PORT:      ${NEPTUNE_PORT}
            LOD_BASE_URL:      ${LOD_BASE_URL}
            FLASK_ENV:         ${FLASK_ENV}
            FLASK_DEBUG:       ${FLASK_DEBUG}
            FLASK_APP:         ${FLASK_APP}
            WEB_SERVICE_PORT:  ${WEB_SERVICE_PORT}
            WEB_DEBUG_HEADER:  ${WEB_DEBUG_HEADER}
            UWSGI_PROCESSES:   ${UWSGI_PROCESSES}
            UWSGI_THREADS:     ${UWSGI_THREADS}
        volumes:
            # use a volume mount to dynamically bind the application's source code
            - ./source/web-service/startup.py:/startup.py
            - ./source/web-service/startup.sh:/startup.sh
            - ./source/web-service/app:/app
            - ./source/web-service/tests:/tests
            # use a volume mount to dynamically bind the shared dependency injector code
            - ./source/app/di:/app/di
            # use a volume mount to dynamically bind the shared database code
            - ./source/app/database:/app/database
            # use a volume mount to dynamically bind the shared graph store code
            - ./source/app/graph:/app/graph
            # use a volume mount to dynamically bind the shared model code
            - ./source/app/model:/app/model
            # use a volume mount to dynamically bind the shared utilities code
            - ./source/app/utilities:/app/utilities
            # use a volume mount to dynamically bind the data path
            - ./data:/usr/local/mart/data
            # use a volume mount to dynamically bind the tests path
            - ./tests:/usr/local/mart/tests
        ports:
            - "${WEB_SERVICE_PORT}:5100"
        links:
            - postgres:postgres

volumes:
    data_postgres:
