version: 2

# define our test jobs
jobs:
    build:
        machine: true
            docker_layer_caching: true
        
        steps:
            - checkout
            - run: mkdir -p /tmp/test-results
            - run: docker build -t lod-gateway-web-service -f Dockerfile.web-service .
            - run: docker run --env-file .env.example --volume /tmp/test-results:/test-results lod-gateway-web-service pytest --junitxml=/test-results/pytest/junit.xml

            - store_test_results:
                path: /tmp/test-results

            - store_artifacts:
                path: /tmp/test-reports