version: 2

# define our test jobs
jobs:
    build:
        machine: 
            docker_layer_caching: true
        
        steps:
            - checkout
            - run: mkdir -p /tmp/output
            - run: docker build -t lod-gateway-web-service -f Dockerfile.web-service .

            # Validate code linting using Black 
            - run: docker run lod-gateway-web-service black --check .

            # Run unit tests using pytest
            - run: >
                docker run
                --env-file .env.example 
                --env DATABASE=sqlite://
                --volume /tmp/output:/output 
                lod-gateway-web-service 
                pytest 
                --junitxml=/output/test-results/pytest/junit.xml 
                --cov=flaskapp 
                --cov-report html:/output/test-reports/pytest

            - store_test_results:
                path: /tmp/output/test-results

            - store_artifacts:
                path: /tmp/output/test-reports
                destination: reports