"""Initial migration.

Revision ID: 411e0b2175f8
Revises: 
Create Date: 2020-02-28 15:34:14.295293

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "411e0b2175f8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=True),
        sa.Column("datetime_created", sa.TIMESTAMP(), nullable=False),
        sa.Column("datetime_updated", sa.TIMESTAMP(), nullable=False),
        sa.Column("datetime_deleted", sa.TIMESTAMP(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_records_entity_id"), "records", ["entity_id"], unique=True)
    op.create_table(
        "activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("datetime_created", sa.TIMESTAMP(), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("event", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["records.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activities_record_id"), "activities", ["record_id"], unique=False
    )
    op.create_index(op.f("ix_activities_uuid"), "activities", ["uuid"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activities_uuid"), table_name="activities")
    op.drop_index(op.f("ix_activities_record_id"), table_name="activities")
    op.drop_table("activities")
    op.drop_index(op.f("ix_records_entity_id"), table_name="records")
    op.drop_table("records")
    # ### end Alembic commands ###
