"""empty message

Revision ID: 463c6598d994
Revises: 3f57f4a875c6
Create Date: 2022-03-10 01:04:12.713551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "463c6598d994"
down_revision = "3f57f4a875c6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=True),
        sa.Column("datetime_created", sa.TIMESTAMP(), nullable=False),
        sa.Column(
            "datetime_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("datetime_deleted", sa.TIMESTAMP(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("checksum", sa.String(), nullable=True),
        sa.Column("record_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["records.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_versions_datetime_created"),
        "versions",
        ["datetime_created"],
        unique=False,
    )
    op.create_index(
        op.f("ix_versions_datetime_updated"),
        "versions",
        ["datetime_updated"],
        unique=False,
    )
    op.create_index(
        op.f("ix_versions_entity_id"), "versions", ["entity_id"], unique=True
    )
    op.create_index(
        op.f("ix_versions_entity_type"), "versions", ["entity_type"], unique=False
    )
    op.create_index(
        op.f("ix_records_datetime_created"),
        "records",
        ["datetime_created"],
        unique=False,
    )
    op.create_index(
        op.f("ix_records_datetime_updated"),
        "records",
        ["datetime_updated"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_records_datetime_updated"), table_name="records")
    op.drop_index(op.f("ix_records_datetime_created"), table_name="records")
    op.drop_index(op.f("ix_versions_entity_type"), table_name="versions")
    op.drop_index(op.f("ix_versions_entity_id"), table_name="versions")
    op.drop_index(op.f("ix_versions_datetime_updated"), table_name="versions")
    op.drop_index(op.f("ix_versions_datetime_created"), table_name="versions")
    op.drop_table("versions")
    # ### end Alembic commands ###
