"""empty message

Revision ID: 51333de9b9b1
Revises: 411e0b2175f8
Create Date: 2020-09-17 21:57:04.487245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm

from flaskapp.models.record import Record
from flaskapp.utilities import checksum_json


# revision identifiers, used by Alembic.
revision = "51333de9b9b1"
down_revision = "411e0b2175f8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("records", sa.Column("checksum", sa.String(), nullable=True))
    # ### end Alembic commands ###
    print("Migration will now checksum existing records - may take some time")
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    while session.query(Record).filter(Record.checksum == None).first() is not None:
        for idx, record in enumerate(
            session.query(Record).filter(Record.checksum == None).limit(100).all()
        ):
            checksum = checksum_json(record.data)
            record.checksum = checksum
            session.add(record)
        session.commit()
        # get count of progress
        done_count = session.query(Record).filter(Record.checksum != None).count()
        print(f"Record count: {done_count} complete")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("records", "checksum")
    # ### end Alembic commands ###
