"""empty message

Revision ID: 51333de9b9b1
Revises: 411e0b2175f8
Create Date: 2020-09-17 21:57:04.487245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm

from flaskapp.models.record import Record
from flaskapp.utilities import checksum_json


# revision identifiers, used by Alembic.
revision = "51333de9b9b1"
down_revision = "411e0b2175f8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("records", sa.Column("checksum", sa.String(), nullable=True))
    # ### end Alembic commands ###
    print("Migration will now checksum existing records - may take some time")
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    for idx, record in enumerate(session.query(Record).all()):
        if idx > 0 and not idx % 100:
            # commit the results every hundred records
            print(f"Up to record {idx+1} - Commiting past changes to db.")
            session.commit()
        checksum = checksum_json(record.data)
        record.checksum = checksum
        session.add(record)
    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("records", "checksum")
    # ### end Alembic commands ###
