"""empty message

Revision ID: 7eb3a9f2a4be
Revises: 463c6598d994
Create Date: 2022-03-23 22:22:27.090710

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7eb3a9f2a4be"
down_revision = "463c6598d994"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_records_record_id_and_type",
        "records",
        ["entity_id", "entity_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_records_record_id_and_type", table_name="records")
    # ### end Alembic commands ###
