"""empty message

Revision ID: 95195abeb123
Revises: 51333de9b9b1
Create Date: 2020-10-20 12:15:14.229592

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm

from flaskapp.models.record import Record


# revision identifiers, used by Alembic.
revision = "95195abeb123"
down_revision = "51333de9b9b1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "records", sa.Column("previous_version", sa.String(), nullable=True, index=True)
    )
    op.add_column(
        "records",
        sa.Column("is_old_version", sa.Boolean(), nullable=True, default=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("records", "checksum")
    op.drop_column("records", "checksum")
    # ### end Alembic commands ###
